// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgojpowqpydsuskzhyrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnb2pwb3dxcHlkc3Vza3poeXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyODExMzEsImV4cCI6MjA5MDg1NzEzMX0.i39ACmsFAwOv7TOiSLFdmbVkRa0DOoHI8SDXeK9Ptns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});